export const REGISTER_BEGIN = "USER_REGISTER_BEGIN";
export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_FAIL = "USER_REGISTER_FAIL";

export const LOGIN_BEGIN = "USER_LOGIN"
export const LOGIN_SUCCESS = "USER_SUCCESS";
export const LOGIN_FAIL = "USER_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL"
export const GET_USER_ID = "GET_USER_ID"

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"

export const GET_POST_BEGIN = "GET_POST_BEGIN"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAIL = "GET_POST_FAIL"

export const POST_EVENT_BEGIN = "POST_EVENT_BEGIN"
export const POST_EVENT_SUCCESS = "POST_EVENT_SUCCESS"
export const POST_EVENT_FAIL = "POST_EVENT_FAIL"

// export const UPDATE_EVENT_BEGIN = "UPDATE_EVENT_BEGIN"
// export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS"
// export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL"

// export const DELETE_EVENT_BEGIN = "DELETE_EVENT_BEGIN"
// export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS"
// export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL"

export const POST_ANNOUNCEMENT_BEGIN = "POST_ANNOUNCEMENT_BEGIN"
export const POST_ANNOUNCEMENT_SUCCESS = "POST_ANNOUNCEMENT_SUCCESS"
export const POST_ANNOUNCEMENT_FAIL = "POST_ANNOUNCEMENT_FAIL"

export const UPDATE_ANNOUNCEMENT_BEGIN = "UPDATE_ANNOUNCEMENT_BEGIN"
export const UPDATE_ANNOUNCEMENT_SUCCESS = "UPDATE_ANNOUNCEMENT_SUCCESS"
export const UPDATE_ANNOUNCEMENT_FAIL = "UPDATE_ANNOUNCEMENT_FAIL"

export const DELETE_ANNOUNCEMENT_BEGIN = "DELETE_ANNOUNCEMENT_BEGIN"
export const DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS"
export const DELETE_ANNOUNCEMENT_FAIL = "DELETE_ANNOUNCEMENT_FAIL"

export const GET_COMMENT_BEGIN = "GET_COMMENT_BEGIN"
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL"

export const BASE_URL_CROWDFINDER = "https://crowdfinder.gabatch13.my.id/api"
export const GET_USER_CROWDFINDER = "https://crowdfinder.gabatch13.my.id/api/user/me"
export const GET_USER_DETAIL_CROWDFINDER = "https://crowdfinder.gabatch13.my.id/api/user"